/**
 * Generated by the @ai-ecoverse/cherry preview-bootstrap build.
 * Task 10 will replace this placeholder with the real single-IIFE bundle.
 * DO NOT hand-edit — this file is build-generated.
 */
export const PREVIEW_BRIDGE_JS =
  '/* slicc preview bridge bootstrap placeholder — window.__slicc */';
