/**
 * Azure AI Foundry — Claude models via Azure's Anthropic endpoint.
 *
 * Registers 'azure-ai-foundry-anthropic' as an API that delegates to
 * pi-ai's standard Anthropic stream functions. The custom API name is
 * generated by provider-settings.ts when getModelIds is present.
 */

import type { ProviderConfig } from '../types.js';
import { registerApiProvider, streamAnthropic, streamSimpleAnthropic } from '@mariozechner/pi-ai';
import type { Api } from '@mariozechner/pi-ai';

export const config: ProviderConfig = {
  id: 'azure-ai-foundry',
  name: 'Azure (Claude)',
  description: 'Claude models via Azure AI Foundry',
  requiresApiKey: true,
  apiKeyPlaceholder: 'Azure API key',
  apiKeyEnvVar: 'AZURE_API_KEY',
  requiresBaseUrl: true,
  baseUrlPlaceholder: 'https://your-resource.services.ai.azure.com/anthropic',
  baseUrlDescription: 'Azure AI Foundry endpoint — must end with /anthropic',
  getModelIds: () => [
    { id: 'claude-opus-4-7', name: 'Claude Opus 4.7', reasoning: true, input: ['text', 'image'] },
    { id: 'claude-opus-4-6', name: 'Claude Opus 4.6', reasoning: true, input: ['text', 'image'] },
    {
      id: 'claude-sonnet-4-6',
      name: 'Claude Sonnet 4.6',
      reasoning: true,
      input: ['text', 'image'],
    },
    {
      id: 'claude-sonnet-4-5',
      name: 'Claude Sonnet 4.5',
      reasoning: true,
      input: ['text', 'image'],
    },
    { id: 'claude-haiku-4-5', name: 'Claude Haiku 4.5', reasoning: true, input: ['text', 'image'] },
  ],
  defaultModelId: 'claude-sonnet-4-6',
};

export function register(): void {
  const api = 'azure-ai-foundry-anthropic' as Api;
  registerApiProvider({
    api,
    stream: streamAnthropic as Parameters<typeof registerApiProvider>[0]['stream'],
    streamSimple: streamSimpleAnthropic as Parameters<
      typeof registerApiProvider
    >[0]['streamSimple'],
  });
}
