import { describe, expect, it } from 'vitest';
import {
  AI_GENERATED_LABEL,
  classifyComment,
  decideLabels,
  findAgentProse,
  findAiSignature,
  HOUSE_HEADING_THRESHOLD,
  HUMAN_IN_THE_LOOP_LABEL,
  interpretPangram,
  isBotAccount,
  isBotLogin,
  isRetryablePangramStatus,
  isThreadSettledHuman,
  jaccardSimilarity,
  MARKDOWN_DENSITY_THRESHOLD,
  machineFormatting,
  markdownCounts,
  markdownDensity,
  maxSimilarity,
  STRUCTURAL_HEADING_THRESHOLD,
  STRUCTURAL_LIST_THRESHOLD,
  tokenize,
} from './lib.mjs';

describe('isBotLogin', () => {
  it('flags [bot] suffixes and known bot logins', () => {
    expect(isBotLogin('dependabot[bot]')).toBe(true);
    expect(isBotLogin('renovate')).toBe(true);
    expect(isBotLogin('github-actions')).toBe(true);
    expect(isBotLogin('my-ci')).toBe(true);
  });
  it('flags Copilot / Codex app logins even without a [bot] suffix', () => {
    expect(isBotLogin('chatgpt-codex-connector')).toBe(true);
    expect(isBotLogin('copilot-pull-request-reviewer')).toBe(true);
    expect(isBotLogin('copilot-swe-agent')).toBe(true);
  });
  it('does not flag ordinary human logins', () => {
    expect(isBotLogin('trieloff')).toBe(false);
    expect(isBotLogin('octocat')).toBe(false);
  });
  it('tolerates null/undefined/empty', () => {
    expect(isBotLogin(null)).toBe(false);
    expect(isBotLogin('')).toBe(false);
  });
});

describe('isBotAccount', () => {
  it('treats GitHub Bot type and app-token comments as bots', () => {
    expect(isBotAccount({ login: 'someone', type: 'Bot' })).toBe(true);
    expect(isBotAccount({ login: 'someone', viaApp: true })).toBe(true);
  });
  it('falls back to login heuristics for User accounts', () => {
    expect(isBotAccount({ login: 'renovate', type: 'User' })).toBe(true);
    expect(isBotAccount({ login: 'trieloff', type: 'User' })).toBe(false);
  });
});

describe('markdownDensity', () => {
  it('scores heavily formatted text high and plain text zero', () => {
    const formatted = '## Heading\n\n- **bold** item with `code`\n- [link](http://x)\n\n> quote';
    expect(markdownDensity(formatted)).toBeGreaterThan(0.15);
    expect(markdownDensity('lgtm thanks for the fix')).toBe(0);
  });
  it('returns 0 for empty input', () => {
    expect(markdownDensity('')).toBe(0);
    expect(markdownDensity(null)).toBe(0);
  });
});

describe('findAiSignature', () => {
  it('flags Claude Code / Cursor / Copilot product footers', () => {
    expect(findAiSignature('🤖 Generated with [Claude Code](https://claude.com/claude-code)')).toBe(
      'claude-code-emoji-footer'
    );
    expect(findAiSignature('Made with Cursor\n')).toBe('cursor-made-with');
    expect(findAiSignature('Generated by GitHub Copilot')).toBe('copilot-generated');
  });
  it('flags Co-Authored-By agent trailers and agent noreply emails', () => {
    expect(findAiSignature('Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>')).toBe(
      'co-authored-by-agent'
    );
    expect(findAiSignature('Co-authored-by: Cursor <cursoragent@cursor.com>')).toBe(
      'co-authored-by-agent'
    );
  });
  it('flags Codex / Copilot review banners even when the login is stripped', () => {
    expect(findAiSignature('### 💡 Codex Review\n\nHere are some suggestions')).toBe(
      'codex-review-banner'
    );
    expect(
      findAiSignature(
        'Copilot was unable to review this pull request because the user who requested the review has reached their quota limit.'
      )
    ).toBe('copilot-quota');
    expect(findAiSignature('You have reached your Codex usage limits for code reviews.')).toBe(
      'codex-usage-limit'
    );
  });
  it('does not flag a human saying they used a helper', () => {
    expect(findAiSignature('I generated this with a helper script')).toBeNull();
    expect(findAiSignature('lgtm thanks for the fix')).toBeNull();
  });
});

describe('findAgentProse', () => {
  it('flags SHA-stamped follow-up / review-round comments', () => {
    expect(
      findAgentProse(
        '**Follow-up (`28d658e65`):** the click-triggered name form still pushed cards down.'
      )
    ).toBe('follow-up-sha');
    expect(
      findAgentProse('**Review round addressed (`50133bf9b`).** All four Codex findings were real.')
    ).toBe('review-round-sha');
  });
  it('flags harness-capture and rebase status-update shapes', () => {
    expect(
      findAgentProse('Captured live on `ba8b1b86e` in an isolated harness (`PORT=5717`).')
    ).toBe('captured-live-sha');
    expect(findAgentProse('Orchestrator review (minor, non-blocking): extract this.')).toBe(
      'orchestrator-review'
    );
    expect(findAgentProse('### Rebased onto merged `main`; both Codex findings fixed')).toBe(
      'rebased-heading'
    );
  });
  it('flags stacked-PR close notes, CI-triage headings, and automation bodies', () => {
    expect(
      findAgentProse(
        'Superseded by #2262, which now carries the whole stack (phases 1–4) as one linear PR.'
      )
    ).toBe('superseded-by');
    expect(
      findAgentProse('### CI triage + review response\n\nBoth failures were investigated.')
    ).toBe('ci-triage-heading');
    expect(
      findAgentProse('Follow-ups from review (92c042e7a): the rail is now behind a feature flag.')
    ).toBe('follow-ups-from-review');
    expect(
      findAgentProse(
        'Automated nightly bump of `coverage-thresholds.json` toward measured coverage.'
      )
    ).toBe('automation-pr-body');
    expect(
      findAgentProse(
        'Automated follow-up after a merge-queue landing to remove planning artifacts.'
      )
    ).toBe('automation-pr-body');
  });
  it('flags review-response status updates that cite a SHA or P2/P3', () => {
    expect(
      findAgentProse(
        'Both P2 findings addressed in `3750a47` — thanks, the first one was a regression.'
      )
    ).toBe('p-findings-addressed-sha');
    expect(
      findAgentProse(
        'Addressed all three review findings (thanks — the first one was a real hole).'
      )
    ).toBe('addressed-all-findings');
    expect(
      findAgentProse('Follow-up for the last P2 (the `--read-only` override in sliccy:agent).')
    ).toBe('follow-up-last-p');
    expect(
      findAgentProse(
        '@codex review — the three findings above are addressed in 1aa432644 (ack-ordered broadcast).'
      )
    ).toBe('bot-review-mention');
    expect(findAgentProse('@codex review')).toBe('bot-review-mention');
    expect(
      findAgentProse('Fixed in 36075bdfe — you are right, and the reason it matters is the same.')
    ).toBe('fixed-in-sha');
    expect(findAgentProse('Implemented in `7f35e4a` (branch rebased onto `main`).')).toBe(
      'implemented-in-sha'
    );
    expect(findAgentProse('Live proof, now that this is on main.')).toBe('live-proof');
  });
  it('does not flag a human review note', () => {
    expect(findAgentProse('Please extract this into a helper.')).toBeNull();
    expect(findAgentProse('lgtm thanks for the fix')).toBeNull();
    expect(
      findAgentProse(
        'please provide screenshots of the file listing side rail in a narrow and wide side rail, so that we can evaluate the responsive design'
      )
    ).toBeNull();
    expect(
      findAgentProse(
        'There is an important caveat and it means a scope extension: switching model providers can have a cost impact.'
      )
    ).toBeNull();
  });
});

describe('machineFormatting', () => {
  it('flags a filled house template whose density is diluted below 0.12', () => {
    // Mirrors slicc#2337: house headings + checklist, density just under 0.12.
    const body = `## Summary

Raise the macOS release job timeout-minutes from 30 to 60 so semantic-release publish can finish worker deploy plus native packaging without being cancelled mid-run.

## Why

Release runs since the File Provider merge hit the 30-minute job ceiling during publish and were cancelled before GitHub Release assets uploaded. Tags exist on main, but the GitHub Releases page still shows an older latest. The last successful release job finished in about 24 minutes.

## Approach / Implementation notes

- Single workflow change in the release workflow with an inline comment citing the regression window.

## Cross-cutting impact

- Floats exercised: CI release pipeline only.
- No runtime, shell, or extension behavior changes.

## Test plan

- [ ] Merge and re-run the Release workflow via workflow_dispatch on main.
- [ ] Confirm the release job completes within 60 minutes and publishes GitHub Release assets.
- [x] N/A — workflow-only change; no unit tests apply.

## Documentation

- [x] No documentation changes needed

## Risk & rollback

- Blast radius: release job may run longer on failure instead of failing fast at 30m.
- Rollback: revert this PR.

## Checklist

- [x] Commits are focused and package-local where possible
- [x] No hand-edited files under dist/
- [x] No secrets, credentials, OAuth client secrets, or tokens in the diff
- [x] Public API / tool / shell-command / lick-channel changes are intentional
- [x] If this changes a contract used by other floats, I checked the follower paths`;
    const counts = markdownCounts(body);
    expect(counts.density).toBeLessThan(MARKDOWN_DENSITY_THRESHOLD);
    expect(counts.headings).toBeGreaterThanOrEqual(STRUCTURAL_HEADING_THRESHOLD);
    expect(counts.lists).toBeGreaterThanOrEqual(STRUCTURAL_LIST_THRESHOLD);
    const flagged = machineFormatting(body);
    expect(flagged).toMatchObject({ flagged: true, method: 'markdown-structure' });
  });
  it('flags a 3-heading + checklist body whose density is still below 0.12', () => {
    const body = `Closes #2232

## What

On a mode attribute change the shader calls linkMode to switch to the cached program. If that returns false, control fell through to the fallback background without touching the program pointer, so the next frame drew the previous mode.

## Why

The finding is low severity because the fragment sources are hardcoded and compile-verified, so this realistically only triggers under an already-dying GL context. A silent stale render with no signal is exactly the kind of thing the diagnostic makes debuggable.

## Test plan

- [x] unit test covers the linkMode false path
- [x] existing shader suite still passes
- [ ] manual smoke on the freezer shader playground
- [x] no documentation changes needed`;
    const counts = markdownCounts(body);
    expect(counts.density).toBeLessThan(MARKDOWN_DENSITY_THRESHOLD);
    expect(counts.headings).toBeGreaterThanOrEqual(STRUCTURAL_HEADING_THRESHOLD);
    expect(counts.lists).toBeGreaterThanOrEqual(STRUCTURAL_LIST_THRESHOLD);
    expect(machineFormatting(body)).toMatchObject({ flagged: true, method: 'markdown-structure' });
  });
  it('flags a house-template body with three named headings even without four lists', () => {
    const body = `## Summary

Adds a probe_extra_ids input to the model scout's manual dispatch, so the invalid path can be exercised against real Bedrock on demand. The extra IDs are probed and logged but never enter the results.

## Why

The scout's first live run worked: both reachable IDs returned 200. That verifies the ok path. It verifies none of the behaviour anyone depends on. The invalid path is the only one that ever alerts a human.

## Verification

npm run verify 7/7. I will dispatch the self-test once this is on main and post what real Bedrock returns.`;
    const counts = markdownCounts(body);
    expect(counts.lists).toBeLessThan(STRUCTURAL_LIST_THRESHOLD);
    expect(counts.houseHeadings).toBeGreaterThanOrEqual(HOUSE_HEADING_THRESHOLD);
    expect(machineFormatting(body)).toMatchObject({ flagged: true, method: 'markdown-structure' });
  });
  it('does not flag a short human reply', () => {
    expect(machineFormatting('lgtm thanks for the fix').flagged).toBe(false);
  });
});

describe('similarity', () => {
  it('tokenizes into a lowercased word set', () => {
    expect(tokenize('Hello, WORLD hello')).toEqual(new Set(['hello', 'world']));
  });
  it('computes jaccard similarity', () => {
    expect(jaccardSimilarity(tokenize('a b c'), tokenize('a b c'))).toBe(1);
    expect(jaccardSimilarity(tokenize('a b'), tokenize('c d'))).toBe(0);
  });
  it('finds the max similarity against a corpus', () => {
    const sim = maxSimilarity('the build is green', ['the build is green', 'totally different']);
    expect(sim).toBe(1);
    expect(maxSimilarity('', ['anything'])).toBe(0);
  });
});

describe('interpretPangram', () => {
  it('reads the async task schema (fraction_ai + assisted)', () => {
    const v = interpretPangram({
      stage: 'STAGE_SUCCESS',
      fraction_ai: 0.7,
      fraction_ai_assisted: 0.2,
    });
    expect(v).toEqual({ isAi: true, score: expect.closeTo(0.9, 5), available: true });
  });
  it('reads the v3 sync schema (ai_likelihood)', () => {
    expect(interpretPangram({ ai_likelihood: 0.1 }).isAi).toBe(false);
    expect(interpretPangram({ ai_likelihood: 0.9 }).isAi).toBe(true);
  });
  it('marks failed/empty results unavailable', () => {
    expect(interpretPangram({ stage: 'STAGE_FAILED' }).available).toBe(false);
    expect(interpretPangram(null).available).toBe(false);
  });
});

describe('isRetryablePangramStatus', () => {
  it('retries transient rate-limit and server errors', () => {
    expect(isRetryablePangramStatus(429)).toBe(true);
    expect(isRetryablePangramStatus(500)).toBe(true);
    expect(isRetryablePangramStatus(503)).toBe(true);
    expect(isRetryablePangramStatus(599)).toBe(true);
  });
  it('does not retry terminal client errors', () => {
    for (const status of [400, 401, 402, 403, 404, 413, 422]) {
      expect(isRetryablePangramStatus(status)).toBe(false);
    }
  });
});

describe('classifyComment (cascade)', () => {
  it('short-circuits on a bot account without calling pangram', async () => {
    let called = false;
    const v = await classifyComment({
      login: 'renovate',
      body: 'plain text',
      pangram: async () => {
        called = true;
        return {};
      },
    });
    expect(v.isHuman).toBe(false);
    expect(v.method).toBe('account');
    expect(called).toBe(false);
  });
  it('flags heavy markdown before reaching pangram', async () => {
    const v = await classifyComment({
      login: 'human',
      body: '## H\n- **a** `b`\n- [c](http://d)\n> q',
      pangram: async () => ({ fraction_ai: 0 }),
    });
    expect(v.method).toBe('markdown-density');
    expect(v.isHuman).toBe(false);
  });
  it('flags moderately formatted prose at the tuned 0.12 threshold', async () => {
    // ~0.125 density: above the tuned 0.12 threshold, below the old 0.15 one.
    const body =
      'We should refactor this **helper** and move the `parse` call into the utils module sometime soon';
    expect(markdownDensity(body)).toBeGreaterThanOrEqual(MARKDOWN_DENSITY_THRESHOLD);
    expect(markdownDensity(body)).toBeLessThan(0.15);
    const v = await classifyComment({
      login: 'human',
      body,
      pangram: async () => ({ fraction_ai: 0 }),
    });
    expect(v.method).toBe('markdown-density');
    expect(v.isHuman).toBe(false);
  });
  it('flags a Claude Code footer before reaching pangram', async () => {
    let called = false;
    const v = await classifyComment({
      login: 'trieloff',
      body: 'Closes #2313.\n\n## Summary\n\nA fake-LLM suite.\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)\n',
      pangram: async () => {
        called = true;
        return { fraction_ai: 0 };
      },
    });
    expect(v).toMatchObject({ isHuman: false, method: 'signature' });
    expect(called).toBe(false);
  });
  it('flags SHA-stamped agent follow-ups before reaching pangram', async () => {
    let called = false;
    const v = await classifyComment({
      login: 'trieloff',
      body: '**Follow-up (`28d658e65`):** both cone actions are now a dialog on the body.',
      pangram: async () => {
        called = true;
        return { fraction_ai: 0 };
      },
    });
    expect(v).toMatchObject({ isHuman: false, method: 'agent-prose', reason: 'follow-up-sha' });
    expect(called).toBe(false);
  });
  it('flags a density-diluted house template via markdown-structure', async () => {
    const body = `## Summary

Raise the macOS release job timeout-minutes from 30 to 60 so semantic-release publish can finish worker deploy plus native packaging without being cancelled mid-run.

## Why

Release runs since the File Provider merge hit the 30-minute job ceiling during publish and were cancelled before GitHub Release assets uploaded. Tags exist on main, but the GitHub Releases page still shows an older latest. The last successful release job finished in about 24 minutes.

## Approach / Implementation notes

- Single workflow change in the release workflow with an inline comment citing the regression window.

## Cross-cutting impact

- Floats exercised: CI release pipeline only.
- No runtime, shell, or extension behavior changes.

## Test plan

- [ ] Merge and re-run the Release workflow via workflow_dispatch on main.
- [ ] Confirm the release job completes within 60 minutes and publishes GitHub Release assets.
- [x] N/A — workflow-only change; no unit tests apply.

## Documentation

- [x] No documentation changes needed

## Risk & rollback

- Blast radius: release job may run longer on failure instead of failing fast at 30m.
- Rollback: revert this PR.

## Checklist

- [x] Commits are focused and package-local where possible
- [x] No hand-edited files under dist/
- [x] No secrets, credentials, OAuth client secrets, or tokens in the diff
- [x] Public API / tool / shell-command / lick-channel changes are intentional
- [x] If this changes a contract used by other floats, I checked the follower paths`;
    expect(markdownDensity(body)).toBeLessThan(MARKDOWN_DENSITY_THRESHOLD);
    const v = await classifyComment({
      login: 'trieloff',
      body,
      pangram: async () => ({ fraction_ai: 0 }),
    });
    expect(v).toMatchObject({ isHuman: false, method: 'markdown-structure' });
  });
  it('treats an empty body as non-human so it cannot stick human-in-the-loop', async () => {
    const v = await classifyComment({
      login: 'trieloff',
      body: '   ',
      pangram: async () => ({ fraction_ai: 0 }),
    });
    expect(v).toMatchObject({ isHuman: false, method: 'empty' });
  });
  it('flags near-duplicate comments via similarity', async () => {
    const v = await classifyComment({
      login: 'human',
      body: 'ci is green and ready to merge',
      corpus: ['ci is green and ready to merge'],
      pangram: async () => ({ fraction_ai: 0 }),
    });
    expect(v.method).toBe('similarity');
  });
  it('falls back to pangram and honours its verdict', async () => {
    const ai = await classifyComment({
      login: 'h',
      body: 'genuine prose here',
      pangram: async () => ({ ai_likelihood: 0.95 }),
    });
    expect(ai).toMatchObject({ isHuman: false, method: 'pangram' });
    const human = await classifyComment({
      login: 'h',
      body: 'genuine prose here',
      pangram: async () => ({ ai_likelihood: 0.05 }),
    });
    expect(human).toMatchObject({ isHuman: true, method: 'pangram' });
  });
  it('defaults to human when pangram is unavailable', async () => {
    const v = await classifyComment({ login: 'h', body: 'genuine prose here' });
    expect(v).toMatchObject({ isHuman: true, method: 'default-human' });
  });
});

describe('decideLabels', () => {
  it('labels a fully AI thread ai-generated', () => {
    expect(decideLabels([{ isHuman: false }, { isHuman: false }])).toEqual({
      add: [AI_GENERATED_LABEL],
      remove: [HUMAN_IN_THE_LOOP_LABEL],
    });
  });
  it('labels a thread with any human contribution human-in-the-loop', () => {
    expect(decideLabels([{ isHuman: false }, { isHuman: true }])).toEqual({
      add: [HUMAN_IN_THE_LOOP_LABEL],
      remove: [AI_GENERATED_LABEL],
    });
  });
  it('does nothing for an empty thread', () => {
    expect(decideLabels([])).toEqual({ add: [], remove: [] });
  });
});

describe('isThreadSettledHuman', () => {
  it('is true when human-in-the-loop is already on the thread', () => {
    expect(isThreadSettledHuman([HUMAN_IN_THE_LOOP_LABEL])).toBe(true);
    expect(isThreadSettledHuman(['something-else', HUMAN_IN_THE_LOOP_LABEL])).toBe(true);
  });
  it('is false when the label is absent', () => {
    expect(isThreadSettledHuman([])).toBe(false);
    expect(isThreadSettledHuman([AI_GENERATED_LABEL])).toBe(false);
    expect(isThreadSettledHuman()).toBe(false);
  });
});
