/*
 * AI-comment detection — pure logic.
 *
 * Classifies each contribution on a PR thread (the PR body plus every comment
 * and review) as human or bot/AI, then decides which thread label applies. The
 * classifier runs a cost-ordered cascade — cheap account checks first, then
 * explicit AI-attribution signatures, coding-agent prose markers, markdown
 * density / structure, then similarity to sibling comments, and only as a last
 * resort an injected Pangram AI-detection call. This module is free of I/O so
 * it can be unit-tested in isolation; the GitHub and Pangram network calls live
 * in `detect-comment-authors.mjs`.
 */

export const AI_GENERATED_LABEL = 'ai-generated';
export const HUMAN_IN_THE_LOOP_LABEL = 'human-in-the-loop';

/** Logins we always treat as bots regardless of the other signals. */
export const DEFAULT_BOT_LOGINS = new Set(
  [
    'github-actions',
    'dependabot',
    'renovate',
    'codecov',
    'copilot',
    'github-copilot',
    'copilot-pull-request-reviewer',
    'copilot-swe-agent',
    'chatgpt-codex-connector',
    'claude',
    'claude-bot',
    'codex',
    'cursor',
    'devin',
    'sweep',
    'augment',
    'augment-agent',
    'augment-code',
  ].map((s) => s.toLowerCase())
);

const BOT_LOGIN_PATTERNS = [/\[bot\]$/i, /-bot$/i, /^bot-/i, /-ci$/i, /^copilot-/i, /^chatgpt-/i];

/** Markdown feature patterns; their match count drives the density score. */
const MARKDOWN_PATTERNS = [
  /\*\*[^*\n]+\*\*/g, // bold
  /__[^_\n]+__/g, // bold (underscore)
  /`[^`\n]+`/g, // inline code
  /```/g, // code fence
  /^\s{0,3}#{1,6}\s/gm, // heading
  /^\s*[-*+]\s+/gm, // unordered list item
  /^\s*\d+\.\s+/gm, // ordered list item
  /\[[^\]\n]+\]\([^)\n]+\)/g, // link
  /^\s*>\s?/gm, // blockquote
  /^\s*\|.*\|\s*$/gm, // table row
  /^\s*([-*_])\1{2,}\s*$/gm, // horizontal rule
];

const HEADING_PATTERN = /^\s{0,3}#{1,6}\s/gm;
const UNORDERED_LIST_PATTERN = /^\s*[-*+]\s+/gm;
const ORDERED_LIST_PATTERN = /^\s*\d+\.\s+/gm;

/**
 * Product footers, commit trailers, and bot-review banners that are themselves
 * the authorship claim. Kept strict so "I generated this with a helper" does
 * not fire. Each entry is `[regex, reason]`; regexes must not be `/g` (so
 * `RegExp#test` is safe to call repeatedly).
 */
export const AI_SIGNATURE_PATTERNS = [
  [/🤖\s*Generated with\b/i, 'claude-code-emoji-footer'],
  [/Generated with \[Claude Code\]/i, 'claude-code-link-footer'],
  [/Generated with Claude Code\b/i, 'claude-code-text-footer'],
  [/Made with Cursor\b/i, 'cursor-made-with'],
  [/Made-with:\s*Cursor\b/i, 'cursor-made-with-header'],
  [/Generated by GitHub Copilot/i, 'copilot-generated'],
  [
    /Co-Authored-By:\s*(?:Claude|Cursor|Codex|Copilot|OpenAI|Devin|Amp|Aider|Cline|Windsurf|Continue|Goose|Gemini)\b/i,
    'co-authored-by-agent',
  ],
  [
    /<(?:cursoragent@cursor\.com|noreply@anthropic\.com|noreply@openai\.com)>/i,
    'agent-noreply-email',
  ],
  [/\*\*Claude finished @/i, 'claude-finished-task'],
  [/###\s*💡\s*Codex Review/i, 'codex-review-banner'],
  [/Copilot was unable to review this pull request/i, 'copilot-quota'],
  [/Codex usage limits for code reviews/i, 'codex-usage-limit'],
];

/**
 * High-precision coding-agent comment shapes posted through a human GitHub
 * login (BB / Claude Code / Cursor follow-ups). SHA-stamped status updates
 * and harness-capture writeups are not how people leave a review note.
 */
export const AGENT_PROSE_PATTERNS = [
  [/\*\*Follow-up\s*\(`[0-9a-f]{7,40}`\):?\*\*/i, 'follow-up-sha'],
  [/\*\*Review round addressed\s*\(`[0-9a-f]{7,40}`\)/i, 'review-round-sha'],
  [/Captured live on\s+`[0-9a-f]{7,40}`/i, 'captured-live-sha'],
  [/\bHead is now\s+`[0-9a-f]{7,40}`/i, 'head-is-now-sha'],
  [/\bMerged as\s+`[0-9a-f]{7,40}`/i, 'merged-as-sha'],
  [/^Orchestrator review\b/im, 'orchestrator-review'],
  [/\bisolated harness\b/i, 'isolated-harness'],
  [/\blive harness\b/i, 'live-harness'],
  [/findings fixed\s*\(`[0-9a-f]{7,40}`\)/i, 'findings-fixed-sha'],
  [/^#{1,3}\s+Live-harness findings\b/im, 'live-harness-findings'],
  [/^#{1,3}\s+Rebased (?:on|onto)\b/im, 'rebased-heading'],
  [/^#{1,3}\s+CI triage\b/im, 'ci-triage-heading'],
  [/^Follow-ups from review\b/im, 'follow-ups-from-review'],
  [/^Superseded by #\d+/im, 'superseded-by'],
  [
    /^Automated (?:nightly bump of `coverage-thresholds\.json`|follow-up after a merge-queue)/i,
    'automation-pr-body',
  ],
  [/\bP[123] findings addressed in\s+`?[0-9a-f]{7,40}`?/i, 'p-findings-addressed-sha'],
  [/Addressed all .{0,30}review findings/i, 'addressed-all-findings'],
  [/^Follow-up for the last P[123]\b/im, 'follow-up-last-p'],
  [/^@codex review\b[\s\S]{0,160}\baddressed in\b/i, 'codex-review-addressed'],
];

/**
 * True if a login looks like a bot account (suffix/prefix patterns or a
 * known bot login). Tolerant of null/undefined.
 * @param {string|null|undefined} login
 * @param {Set<string>} [knownBots]
 */
export function isBotLogin(login, knownBots = DEFAULT_BOT_LOGINS) {
  const name = String(login ?? '').trim();
  if (!name) return false;
  if (knownBots.has(name.toLowerCase())) return true;
  return BOT_LOGIN_PATTERNS.some((re) => re.test(name));
}

/**
 * Cheap account-level bot check: GitHub user `type === 'Bot'`, a comment made
 * through a GitHub App (app token), or a bot-looking login.
 * @param {{login?: string, type?: string, viaApp?: boolean}} author
 * @param {Set<string>} [knownBots]
 */
export function isBotAccount({ login, type, viaApp } = {}, knownBots = DEFAULT_BOT_LOGINS) {
  if (type && String(type).toLowerCase() === 'bot') return true;
  if (viaApp) return true;
  return isBotLogin(login, knownBots);
}

/**
 * Count markdown features used by the density and structure heuristics.
 * @param {string|null|undefined} text
 * @returns {{words: number, features: number, headings: number, lists: number, density: number}}
 */
export function markdownCounts(text) {
  const body = String(text ?? '');
  const words = body.split(/\s+/).filter(Boolean).length;
  let features = 0;
  for (const re of MARKDOWN_PATTERNS) {
    const m = body.match(re);
    if (m) features += m.length;
  }
  const headings = (body.match(HEADING_PATTERN) || []).length;
  const lists =
    (body.match(UNORDERED_LIST_PATTERN) || []).length +
    (body.match(ORDERED_LIST_PATTERN) || []).length;
  return { words, features, headings, lists, density: words === 0 ? 0 : features / words };
}

/**
 * Markdown-formatting density: number of markdown feature occurrences per word.
 * Heavily formatted comments (many headings/bullets/bold) score high.
 * @param {string|null|undefined} text
 * @returns {number} occurrences per word (0 for empty text)
 */
export function markdownDensity(text) {
  return markdownCounts(text).density;
}

/**
 * First matching AI-attribution signature in `text`, or `null`.
 * @param {string|null|undefined} text
 * @returns {string|null} reason tag
 */
export function findAiSignature(text) {
  const body = String(text ?? '');
  if (!body) return null;
  for (const [re, reason] of AI_SIGNATURE_PATTERNS) {
    if (re.test(body)) return reason;
  }
  return null;
}

/**
 * First matching coding-agent prose marker in `text`, or `null`.
 * @param {string|null|undefined} text
 * @returns {string|null} reason tag
 */
export function findAgentProse(text) {
  const body = String(text ?? '');
  if (!body) return null;
  for (const [re, reason] of AGENT_PROSE_PATTERNS) {
    if (re.test(body)) return reason;
  }
  return null;
}

/** Lowercased word-token set for similarity comparison. */
export function tokenize(text) {
  return new Set(
    String(text ?? '')
      .toLowerCase()
      .split(/[^a-z0-9]+/)
      .filter(Boolean)
  );
}

/** Jaccard similarity between two token sets (0..1). */
export function jaccardSimilarity(a, b) {
  if (a.size === 0 && b.size === 0) return 0;
  let inter = 0;
  for (const tok of a) if (b.has(tok)) inter += 1;
  const union = a.size + b.size - inter;
  return union === 0 ? 0 : inter / union;
}

/**
 * Highest Jaccard similarity between `text` and any string in `corpus`.
 * @param {string} text
 * @param {string[]} corpus other comment bodies to compare against
 */
export function maxSimilarity(text, corpus = []) {
  const target = tokenize(text);
  if (target.size === 0) return 0;
  let max = 0;
  for (const other of corpus) {
    const sim = jaccardSimilarity(target, tokenize(other));
    if (sim > max) max = sim;
  }
  return max;
}

/**
 * Interpret a Pangram detection result. Supports the async task schema
 * (`fraction_ai` + `fraction_ai_assisted`) and the v3 sync schema
 * (`ai_likelihood`). Returns `available: false` when the result is unusable.
 * @param {object|null|undefined} result
 * @param {number} [threshold]
 */
export function interpretPangram(result, threshold = 0.5) {
  if (!result || result.stage === 'STAGE_FAILED')
    return { isAi: false, score: 0, available: false };
  const raw =
    result.ai_likelihood ??
    Number(result.fraction_ai ?? 0) + Number(result.fraction_ai_assisted ?? 0);
  const score = Number(raw);
  if (!Number.isFinite(score)) return { isAi: false, score: 0, available: false };
  return { isAi: score >= threshold, score, available: true };
}

/**
 * Whether a Pangram HTTP status is worth retrying: only transient rate-limit
 * (429) or server (5xx) errors. Client errors (400/401/402/403/413/422) are
 * terminal — a retry can't fix a bad key, no credits, or invalid input — so the
 * call fails fast to the human default rather than burning the poll budget.
 * @param {number} status
 */
export function isRetryablePangramStatus(status) {
  return status === 429 || (status >= 500 && status <= 599);
}

/**
 * Markdown-density above which a comment is treated as machine-formatted.
 * Tuned against a 395-contribution sample across the ai-ecoverse org validated
 * with Pangram: at 0.15 the flag was 96% precise but missed AI-written prose
 * clustered in the 0.11–0.15 band (genuine human replies topped out at ~0.105),
 * so 0.12 closes most of that recall gap without crossing the human cluster.
 */
export const MARKDOWN_DENSITY_THRESHOLD = 0.12;
/**
 * Absolute heading + list counts at which a contribution is treated as
 * machine-formatted even when a long filled-in template has diluted per-word
 * density below `MARKDOWN_DENSITY_THRESHOLD`. House PR templates in this repo
 * sit at ~0.118 once filled; shorter agent bodies that keep three of those
 * headings plus a checklist still clear 3+4. Genuine review notes do not.
 */
export const STRUCTURAL_HEADING_THRESHOLD = 3;
export const STRUCTURAL_LIST_THRESHOLD = 4;
/** Jaccard similarity above which a comment is treated as a templated dupe. */
export const SIMILARITY_THRESHOLD = 0.8;

/**
 * Density or heading+list structure that reads as machine-formatted.
 * @param {string|null|undefined} text
 * @returns {{flagged: boolean, method: string|null, score: number}}
 */
export function machineFormatting(text) {
  const counts = markdownCounts(text);
  if (counts.density >= MARKDOWN_DENSITY_THRESHOLD) {
    return { flagged: true, method: 'markdown-density', score: counts.density };
  }
  if (
    counts.headings >= STRUCTURAL_HEADING_THRESHOLD &&
    counts.lists >= STRUCTURAL_LIST_THRESHOLD
  ) {
    return { flagged: true, method: 'markdown-structure', score: counts.headings };
  }
  return { flagged: false, method: null, score: counts.density };
}

/**
 * Classify a single contribution as human or bot/AI by running the cost-ordered
 * cascade: cheap account check, empty body, explicit AI signatures, coding-agent
 * prose, markdown density/structure, then similarity to the sibling corpus, and
 * finally (only if nothing else fired) the injected Pangram call. When Pangram
 * is absent or unavailable the contribution defaults to human so the thread is
 * never labelled AI on a missing signal.
 * @param {object} opts
 * @param {string} [opts.login] author login
 * @param {string} [opts.type] GitHub author type (`User` / `Bot`)
 * @param {boolean} [opts.viaApp] comment posted through a GitHub App token
 * @param {string} [opts.body] comment text
 * @param {string[]} [opts.corpus] sibling comment bodies for similarity
 * @param {(text: string) => Promise<object|null>} [opts.pangram] Pangram caller
 * @param {Set<string>} [opts.knownBots]
 * @returns {Promise<{isHuman: boolean, method: string, score?: number, reason?: string}>}
 */
export async function classifyComment({
  login,
  type,
  viaApp,
  body = '',
  corpus = [],
  pangram,
  knownBots = DEFAULT_BOT_LOGINS,
} = {}) {
  if (isBotAccount({ login, type, viaApp }, knownBots)) {
    return { isHuman: false, method: 'account' };
  }
  if (!String(body ?? '').trim()) {
    return { isHuman: false, method: 'empty' };
  }
  const signature = findAiSignature(body);
  if (signature) {
    return { isHuman: false, method: 'signature', reason: signature };
  }
  const prose = findAgentProse(body);
  if (prose) {
    return { isHuman: false, method: 'agent-prose', reason: prose };
  }
  const formatting = machineFormatting(body);
  if (formatting.flagged) {
    return { isHuman: false, method: formatting.method, score: formatting.score };
  }
  const similarity = maxSimilarity(body, corpus);
  if (similarity >= SIMILARITY_THRESHOLD) {
    return { isHuman: false, method: 'similarity', score: similarity };
  }
  if (typeof pangram === 'function') {
    const verdict = interpretPangram(await pangram(body));
    if (verdict.available) {
      return { isHuman: !verdict.isAi, method: 'pangram', score: verdict.score };
    }
  }
  return { isHuman: true, method: 'default-human' };
}

/**
 * Decide the thread-level labels from per-contribution verdicts. A thread with
 * at least one human contribution is `human-in-the-loop`; a thread that is
 * entirely bot/AI is `ai-generated`. An empty thread changes nothing.
 * @param {Array<{isHuman: boolean}>} verdicts
 * @returns {{add: string[], remove: string[]}}
 */
export function decideLabels(verdicts = []) {
  if (verdicts.length === 0) return { add: [], remove: [] };
  const hasHuman = verdicts.some((v) => v.isHuman);
  return hasHuman
    ? { add: [HUMAN_IN_THE_LOOP_LABEL], remove: [AI_GENERATED_LABEL] }
    : { add: [AI_GENERATED_LABEL], remove: [HUMAN_IN_THE_LOOP_LABEL] };
}

/**
 * `human-in-the-loop` is sticky: once any human has contributed to a thread,
 * later bot/AI activity can never make it fully AI again. So when the label is
 * already present the thread needs no reclassification, and the driver can skip
 * all remaining I/O (comment fetches and Pangram calls) entirely.
 * @param {string[]} currentLabels label names already on the thread
 */
export function isThreadSettledHuman(currentLabels = []) {
  return currentLabels.includes(HUMAN_IN_THE_LOOP_LABEL);
}
