export const AI_GENERATED_LABEL = 'ai-generated';
export const HUMAN_IN_THE_LOOP_LABEL = 'human-in-the-loop';

export const DEFAULT_BOT_LOGINS = new Set(
  [
    'github-actions',
    'dependabot',
    'renovate',
    'codecov',
    'copilot',
    'github-copilot',
    'copilot-pull-request-reviewer',
    'copilot-swe-agent',
    'chatgpt-codex-connector',
    'claude',
    'claude-bot',
    'codex',
    'cursor',
    'devin',
    'sweep',
    'augment',
    'augment-agent',
    'augment-code',
  ].map((s) => s.toLowerCase())
);

const BOT_LOGIN_PATTERNS = [/\[bot\]$/i, /-bot$/i, /^bot-/i, /-ci$/i, /^copilot-/i, /^chatgpt-/i];

const MARKDOWN_PATTERNS = [
  /\*\*[^*\n]+\*\*/g,
  /__[^_\n]+__/g,
  /`[^`\n]+`/g,
  /```/g,
  /^\s{0,3}#{1,6}\s/gm,
  /^\s*[-*+]\s+/gm,
  /^\s*\d+\.\s+/gm,
  /\[[^\]\n]+\]\([^)\n]+\)/g,
  /^\s*>\s?/gm,
  /^\s*\|.*\|\s*$/gm,
  /^\s*([-*_])\1{2,}\s*$/gm,
];

const HEADING_PATTERN = /^\s{0,3}#{1,6}\s/gm;
const UNORDERED_LIST_PATTERN = /^\s*[-*+]\s+/gm;
const ORDERED_LIST_PATTERN = /^\s*\d+\.\s+/gm;

const HOUSE_HEADING_PATTERN =
  /^\s{0,3}#{1,6}\s+(Summary|Why|Approach|Cross-cutting impact|Test plan|Documentation|Risk|Checklist|Verification|What changed|What)\b/gim;

export const AI_SIGNATURE_PATTERNS = [
  [/🤖\s*Generated with\b/i, 'claude-code-emoji-footer'],
  [/Generated with \[Claude Code\]/i, 'claude-code-link-footer'],
  [/Generated with Claude Code\b/i, 'claude-code-text-footer'],
  [/Made with Cursor\b/i, 'cursor-made-with'],
  [/Made-with:\s*Cursor\b/i, 'cursor-made-with-header'],
  [/Generated by GitHub Copilot/i, 'copilot-generated'],
  [
    /Co-Authored-By:\s*(?:Claude|Cursor|Codex|Copilot|OpenAI|Devin|Amp|Aider|Cline|Windsurf|Continue|Goose|Gemini)\b/i,
    'co-authored-by-agent',
  ],
  [
    /<(?:cursoragent@cursor\.com|noreply@anthropic\.com|noreply@openai\.com)>/i,
    'agent-noreply-email',
  ],
  [/\*\*Claude finished @/i, 'claude-finished-task'],
  [/###\s*💡\s*Codex Review/i, 'codex-review-banner'],
  [/Copilot was unable to review this pull request/i, 'copilot-quota'],
  [/Codex usage limits for code reviews/i, 'codex-usage-limit'],
];

export const AGENT_PROSE_PATTERNS = [
  [/\*\*Follow-up\s*\(`[0-9a-f]{7,40}`\):?\*\*/i, 'follow-up-sha'],
  [/\*\*Review round addressed\s*\(`[0-9a-f]{7,40}`\)/i, 'review-round-sha'],
  [/Captured live on\s+`[0-9a-f]{7,40}`/i, 'captured-live-sha'],
  [/\bHead is now\s+`[0-9a-f]{7,40}`/i, 'head-is-now-sha'],
  [/\bMerged as\s+`[0-9a-f]{7,40}`/i, 'merged-as-sha'],
  [/^Orchestrator review\b/im, 'orchestrator-review'],
  [/\bisolated harness\b/i, 'isolated-harness'],
  [/\blive harness\b/i, 'live-harness'],
  [/findings fixed\s*\(`[0-9a-f]{7,40}`\)/i, 'findings-fixed-sha'],
  [/^#{1,3}\s+Live-harness findings\b/im, 'live-harness-findings'],
  [/^#{1,3}\s+Rebased (?:on|onto)\b/im, 'rebased-heading'],
  [/^#{1,3}\s+CI triage\b/im, 'ci-triage-heading'],
  [/^Follow-ups from review\b/im, 'follow-ups-from-review'],
  [/^Superseded by #\d+/im, 'superseded-by'],
  [
    /^Automated (?:nightly bump of `coverage-thresholds\.json`|follow-up after a merge-queue)/i,
    'automation-pr-body',
  ],
  [/\bP[123] findings addressed in\s+`?[0-9a-f]{7,40}`?/i, 'p-findings-addressed-sha'],
  [/Addressed all .{0,30}review findings/i, 'addressed-all-findings'],
  [/^Follow-up for the last P[123]\b/im, 'follow-up-last-p'],
  [/^@(?:codex|claude|copilot) review\b/im, 'bot-review-mention'],
  [/^Fixed in\s+`?[0-9a-f]{7,40}`?/im, 'fixed-in-sha'],
  [/^Implemented in\s+`[0-9a-f]{7,40}`/im, 'implemented-in-sha'],
  [/\bPushed as\s+`[0-9a-f]{7,40}`/i, 'pushed-as-sha'],
  [/^Live proof\b/im, 'live-proof'],
];

export function isBotLogin(login, knownBots = DEFAULT_BOT_LOGINS) {
  const name = String(login ?? '').trim();
  if (!name) return false;
  if (knownBots.has(name.toLowerCase())) return true;
  return BOT_LOGIN_PATTERNS.some((re) => re.test(name));
}

export function isBotAccount({ login, type, viaApp } = {}, knownBots = DEFAULT_BOT_LOGINS) {
  if (type && String(type).toLowerCase() === 'bot') return true;
  if (viaApp) return true;
  return isBotLogin(login, knownBots);
}

export function markdownCounts(text) {
  const body = String(text ?? '');
  const words = body.split(/\s+/).filter(Boolean).length;
  let features = 0;
  for (const re of MARKDOWN_PATTERNS) {
    const m = body.match(re);
    if (m) features += m.length;
  }
  const headings = (body.match(HEADING_PATTERN) || []).length;
  const lists =
    (body.match(UNORDERED_LIST_PATTERN) || []).length +
    (body.match(ORDERED_LIST_PATTERN) || []).length;
  const houseHeadings = (body.match(HOUSE_HEADING_PATTERN) || []).length;
  return {
    words,
    features,
    headings,
    lists,
    houseHeadings,
    density: words === 0 ? 0 : features / words,
  };
}

export function markdownDensity(text) {
  return markdownCounts(text).density;
}

export function findAiSignature(text) {
  const body = String(text ?? '');
  if (!body) return null;
  for (const [re, reason] of AI_SIGNATURE_PATTERNS) {
    if (re.test(body)) return reason;
  }
  return null;
}

export function findAgentProse(text) {
  const body = String(text ?? '');
  if (!body) return null;
  for (const [re, reason] of AGENT_PROSE_PATTERNS) {
    if (re.test(body)) return reason;
  }
  return null;
}

export function tokenize(text) {
  return new Set(
    String(text ?? '')
      .toLowerCase()
      .split(/[^a-z0-9]+/)
      .filter(Boolean)
  );
}

export function jaccardSimilarity(a, b) {
  if (a.size === 0 && b.size === 0) return 0;
  let inter = 0;
  for (const tok of a) if (b.has(tok)) inter += 1;
  const union = a.size + b.size - inter;
  return union === 0 ? 0 : inter / union;
}

export function maxSimilarity(text, corpus = []) {
  const target = tokenize(text);
  if (target.size === 0) return 0;
  let max = 0;
  for (const other of corpus) {
    const sim = jaccardSimilarity(target, tokenize(other));
    if (sim > max) max = sim;
  }
  return max;
}

export function interpretPangram(result, threshold = 0.5) {
  if (!result || result.stage === 'STAGE_FAILED')
    return { isAi: false, score: 0, available: false };
  const raw =
    result.ai_likelihood ??
    Number(result.fraction_ai ?? 0) + Number(result.fraction_ai_assisted ?? 0);
  const score = Number(raw);
  if (!Number.isFinite(score)) return { isAi: false, score: 0, available: false };
  return { isAi: score >= threshold, score, available: true };
}

export function isRetryablePangramStatus(status) {
  return status === 429 || (status >= 500 && status <= 599);
}

export const MARKDOWN_DENSITY_THRESHOLD = 0.12;

export const STRUCTURAL_HEADING_THRESHOLD = 3;
export const STRUCTURAL_LIST_THRESHOLD = 4;

export const HOUSE_HEADING_THRESHOLD = 3;

export const SIMILARITY_THRESHOLD = 0.8;

export function machineFormatting(text) {
  const counts = markdownCounts(text);
  if (counts.density >= MARKDOWN_DENSITY_THRESHOLD) {
    return { flagged: true, method: 'markdown-density', score: counts.density };
  }
  if (
    counts.headings >= STRUCTURAL_HEADING_THRESHOLD &&
    counts.lists >= STRUCTURAL_LIST_THRESHOLD
  ) {
    return { flagged: true, method: 'markdown-structure', score: counts.headings };
  }
  if (counts.houseHeadings >= HOUSE_HEADING_THRESHOLD) {
    return { flagged: true, method: 'markdown-structure', score: counts.houseHeadings };
  }
  return { flagged: false, method: null, score: counts.density };
}

export async function classifyComment({
  login,
  type,
  viaApp,
  body = '',
  corpus = [],
  pangram,
  knownBots = DEFAULT_BOT_LOGINS,
} = {}) {
  if (isBotAccount({ login, type, viaApp }, knownBots)) {
    return { isHuman: false, method: 'account' };
  }
  if (!String(body ?? '').trim()) {
    return { isHuman: false, method: 'empty' };
  }
  const signature = findAiSignature(body);
  if (signature) {
    return { isHuman: false, method: 'signature', reason: signature };
  }
  const prose = findAgentProse(body);
  if (prose) {
    return { isHuman: false, method: 'agent-prose', reason: prose };
  }
  const formatting = machineFormatting(body);
  if (formatting.flagged) {
    return { isHuman: false, method: formatting.method, score: formatting.score };
  }
  const similarity = maxSimilarity(body, corpus);
  if (similarity >= SIMILARITY_THRESHOLD) {
    return { isHuman: false, method: 'similarity', score: similarity };
  }
  if (typeof pangram === 'function') {
    const verdict = interpretPangram(await pangram(body));
    if (verdict.available) {
      return { isHuman: !verdict.isAi, method: 'pangram', score: verdict.score };
    }
  }
  return { isHuman: true, method: 'default-human' };
}

export function decideLabels(verdicts = []) {
  if (verdicts.length === 0) return { add: [], remove: [] };
  const hasHuman = verdicts.some((v) => v.isHuman);
  return hasHuman
    ? { add: [HUMAN_IN_THE_LOOP_LABEL], remove: [AI_GENERATED_LABEL] }
    : { add: [AI_GENERATED_LABEL], remove: [HUMAN_IN_THE_LOOP_LABEL] };
}

export function isThreadSettledHuman(currentLabels = []) {
  return currentLabels.includes(HUMAN_IN_THE_LOOP_LABEL);
}
